schema: 
  - https://api.github.com/graphql:
      headers: 
        Authorization: "bearer ${GITHUB_PAT}"
documents: graphql/**/*.graphql
extensions:
  codegen:
    generates:
      ./infrastructure/graphql/generated-client.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-graphql-request
